language: php
php:
  - 5.5
  - 5.6

before_install:
  - composer update
  - bundle install

before_script:
  - php artisan serve &
  - bundle exec chef-zero -d
  - sleep 3

services:
  - redis-server

script:
  - ./vendor/bin/behat -p travisci
  - ./vendor/bin/phpunit
