language: php
php:
  - hhvm

before_install:
  - composer install
  - bundle install
  - "export DISPLAY=:99.0"
  # - "sh -e /etc/init.d/xvfb start"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb +extension RANDR -- :99 -ac -screen 0 1280x1024x16"
  - sleep 3 # give xvfb some time to start

before_script:
  - php artisan serve &
  - bundle exec chef-zero -d
  - sleep 3

services:
  - redis-server

script:
  - ./vendor/bin/behat -p travisci
  - ./vendor/bin/phpunit
