language: php
php:
  - 5.6

before_install:
  - sudo apt-get install libgecode-dev
  - composer install
  - bundle install --without deploy --jobs=3 --retry=3

before_script:
  - php artisan serve &
  - bundle exec chef-zero -d
  - bundle exec berks update -b app/tests/Berksfile
  - BERKSHELF_CHEF_CONFIG="app/tests/client.rb" bundle exec berks upload --force -b app/tests/Berksfile
  - sleep 3

services:
  - redis-server

script:
  - ./vendor/bin/behat -p travisci
  - ./vendor/bin/phpunit
