language: php
php:
  - 5.5
  - hhvm

before_install:
  - composer install

before_script:
  - php artisan serve &
  - bundle exec chef-zero -d

services:
  - redis-server

script:
  - behat -p travisci
