language: php
php:
  - 5.5
  - 5.6
  - hhvm

before_install:
  - composer install
  - bundle install
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

before_script:
  - php artisan serve &
  - bundle exec chef-zero -d
  - sleep 3

services:
  - redis-server

script:
  - ./vendor/bin/behat -p travisci
