# Load DSL and Setup Up Stages
require 'capistrano/setup'

# Includes default deployment tasks
require 'capistrano/deploy'
require 'capistrano/composer'
require 'capistrano/file-permissions'
require 'capistrano/copy_files'

# Loads custom tasks from `capistrano/tasks' if you have any defined.
Dir.glob('tasks/*.rake').each { |r| import r }
